FROM nginx:alpine

# Copy local config into the image at the correct path
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy code (Nginx needs to see the files to know they exist!)
COPY . /var/www/html/